eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restaurantdb
    username: restaurantprjt
    password: restaurantprjt
