server:
  port: 9090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8998/eureka/

spring:
  application:
    name: Restaurant-Service
  main:
    banner-mode: off #turn off spring boot banner
  datasource:
    url: jdbc:mysql://localhost:3306/restaurantdb
    username: restaurantprjt
    password: restaurantprjt
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update #everytime the server starts it creates new table if in create mode
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect # dialect for converting orm to sql language
#logging:
 # level:
  #  root: warn